language: cpp

os:
  - linux
  - osx

branches:
  only:
    - master

matrix:
  include:
  - compiler: clang
    os: linux
    dist: trusty
    env: 
     - QMAKESPEC=linux-clang
     - QT_BASE=57
  - compiler: gcc
    os: linux
    dist: trusty
    env: 
     - QMAKESPEC=linux-g++
     - QT_BASE=48
  - compiler: gcc
    os: linux
    dist: trusty
    env: 
     - QMAKESPEC=linux-g++
     - QT_BASE=57
  - compiler: clang
    os: osx
    env: 
     - QMAKESPEC=macx-clang
     - QT_BASE=57

before_install:
 - if [[ "$QT_BASE" = "48" && "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:beineri/opt-qt487-trusty; fi
 - if [[ "$QT_BASE" = "57" && "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:beineri/opt-qt571-trusty; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
 - if [[ "$QT_BASE" = "48" && "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq opt-qt4-qmake opt-qt4-dev-tools; source /opt/qt-4.8/bin/qt-4.8-env.sh; fi
 - if [[ "$QT_BASE" = "57" && "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then qmake -r; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/opt/qt/bin/qmake -r; fi
- make
